# Generated by Django 5.2 on 2025-05-17 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hari_praktek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ICD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20)),
                ('nama_diagnosa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('ID_BPJS', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('jenis_kelamin', models.CharField(max_length=10)),
                ('tanggal_lahir', models.DateField()),
                ('nomor_HP', models.CharField(max_length=13)),
                ('email_pasien', models.CharField(max_length=50)),
                ('nomor_urut', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='perawat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perawat', models.CharField(max_length=50)),
                ('password_perawat', models.CharField(max_length=20)),
                ('email_perawat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dokter_spesialis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dokter_spc', models.CharField(max_length=50)),
                ('password_dokter_spc', models.CharField(max_length=20)),
                ('email_dokter_spc', models.CharField(max_length=50)),
                ('spesialization', models.CharField(max_length=100)),
                ('image_dokter_spc', models.CharField(max_length=100)),
                ('schedule_dokter_spc', models.ManyToManyField(related_name='hari_praktek_dokter_spc_set', to='RSUD_KRATON.hari_praktek')),
            ],
        ),
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dokter', models.CharField(max_length=50)),
                ('password_dokter', models.CharField(max_length=20)),
                ('email_dokter', models.CharField(max_length=50)),
                ('image_dokter', models.CharField(max_length=100)),
                ('schedule_dokter', models.ManyToManyField(related_name='hari_praktek_dokter_set', to='RSUD_KRATON.hari_praktek')),
            ],
        ),
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_konsultasi', models.DateField()),
                ('keluhan', models.CharField(max_length=100)),
                ('nama_dokter', models.CharField(max_length=50)),
                ('sesi_praktek_dokter', models.CharField(max_length=50)),
                ('data_pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_bpjs_set', to='RSUD_KRATON.pasien')),
            ],
        ),
        migrations.CreateModel(
            name='sesi_praktek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jam_sesi', models.CharField(max_length=50)),
                ('jam_total', models.IntegerField()),
                ('data_pendaftaran', models.ManyToManyField(blank=True, related_name='data_pendaftaran_set', to='RSUD_KRATON.pendaftaran')),
                ('hari_praktek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hari_praktek_set', to='RSUD_KRATON.hari_praktek')),
            ],
        ),
    ]
