# Generated by Django 5.1.6 on 2025-04-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pasien',
            fields=[
                ('ID_BPJS', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('jenis_kelamin', models.CharField(max_length=10)),
                ('tanggal_lahir', models.DateField()),
                ('nomor_HP', models.CharField(max_length=13)),
                ('email_pasien', models.CharField(max_length=30)),
                ('nomor_antrian', models.IntegerField()),
            ],
        ),
    ]
