# Generated by Django 5.2 on 2025-05-17 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesi_praktek',
            name='data_pendaftaran',
        ),
        migrations.RenameField(
            model_name='dokter_spesialis',
            old_name='email_dokter_spc',
            new_name='email_dokter',
        ),
        migrations.RenameField(
            model_name='dokter_spesialis',
            old_name='image_dokter_spc',
            new_name='image_dokter',
        ),
        migrations.RenameField(
            model_name='dokter_spesialis',
            old_name='nama_dokter_spc',
            new_name='nama_dokter',
        ),
        migrations.RenameField(
            model_name='dokter_spesialis',
            old_name='password_dokter_spc',
            new_name='password_dokter',
        ),
        migrations.RenameField(
            model_name='dokter_spesialis',
            old_name='schedule_dokter_spc',
            new_name='schedule_dokter',
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_konsultasi', models.DateField()),
                ('keluhan', models.CharField(max_length=100)),
                ('diagnosa_sub', models.CharField(max_length=200)),
                ('Dokter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dokter_umum_set', to='RSUD_KRATON.dokter')),
                ('Dokter_spesialis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dokter_spesialis_set', to='RSUD_KRATON.dokter_spesialis')),
                ('diagnosa_primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosa_primary_set', to='RSUD_KRATON.icd')),
                ('diagnosa_secondary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosa_secondary_set', to='RSUD_KRATON.icd')),
            ],
        ),
        migrations.CreateModel(
            name='rekap_medis',
            fields=[
                ('ID_BPJS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pasien_set', serialize=False, to='RSUD_KRATON.pasien')),
                ('history', models.ManyToManyField(related_name='history_set', to='RSUD_KRATON.history')),
            ],
        ),
        migrations.DeleteModel(
            name='Pendaftaran',
        ),
    ]
