# Generated by Django 5.1.7 on 2025-04-24 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dokter', models.IntegerField()),
                ('nama_dokter', models.CharField(max_length=50)),
                ('password_dokter', models.CharField(max_length=20)),
                ('email_dokter', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='hari_praktek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(max_length=50)),
                ('sesi_praktek', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ICD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10)),
                ('nama_diagnosa', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='perawat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_perawat', models.IntegerField()),
                ('nama_perawat', models.CharField(max_length=50)),
                ('password_perawat', models.CharField(max_length=20)),
                ('email_perawat', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='pasien',
            name='nomor_antrian',
        ),
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pendaftaran', models.IntegerField()),
                ('tanggal_konsultasi', models.DateField()),
                ('keluhan', models.CharField(max_length=100)),
                ('nomor_antrian', models.IntegerField()),
                ('hari_konsul_dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hari_konsul_dokter_set', to='RSUD_KRATON.hari_praktek')),
                ('id_bpjs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_bpjs_set', to='RSUD_KRATON.pasien')),
                ('nama_dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nama_dokter_set', to='RSUD_KRATON.dokter')),
                ('nama_pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nama_pasien_set', to='RSUD_KRATON.pasien')),
                ('sesi_praktek_dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesi_praktek_dokter_set', to='RSUD_KRATON.hari_praktek')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penyakit_pasien', models.CharField(max_length=100)),
                ('diagnosa_icd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosa_icd_set', to='RSUD_KRATON.icd')),
                ('kode_icd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kode_icd_set', to='RSUD_KRATON.icd')),
                ('id_pendaftaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_pendaftaran_set', to='RSUD_KRATON.pendaftaran')),
                ('nama_pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nama_pasien_set', to='RSUD_KRATON.pendaftaran')),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jam_total', models.IntegerField()),
                ('data_pasien', models.JSONField(default=list)),
                ('hari_praktek_dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hari_praktek_dokter_set', to='RSUD_KRATON.hari_praktek')),
            ],
        ),
    ]
