# Generated by Django 5.2 on 2025-05-17 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0002_remove_sesi_praktek_data_pendaftaran_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('data_pasien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='id_bpjs_set', serialize=False, to='RSUD_KRATON.pasien')),
                ('tanggal_konsultasi', models.DateField()),
                ('keluhan', models.CharField(max_length=100)),
                ('nama_dokter', models.CharField(max_length=50)),
                ('sesi_praktek_dokter', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='sesi_praktek',
            name='data_pendaftaran',
            field=models.ManyToManyField(blank=True, related_name='data_pendaftaran_set', to='RSUD_KRATON.pendaftaran'),
        ),
    ]
