# Generated by Django 5.2 on 2025-04-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0003_remove_pendaftaran_nomor_antrian'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokter_spesialis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dokter_spc', models.IntegerField()),
                ('nama_dokter_spc', models.CharField(max_length=50)),
                ('password_dokter_spc', models.CharField(max_length=20)),
                ('email_dokter_spc', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameField(
            model_name='pendaftaran',
            old_name='id_bpjs',
            new_name='data_pasien',
        ),
        migrations.RemoveField(
            model_name='pendaftaran',
            name='hari_konsul_dokter',
        ),
        migrations.RemoveField(
            model_name='pendaftaran',
            name='nama_pasien',
        ),
    ]
