# Generated by Django 5.1.7 on 2025-04-26 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0003_remove_pendaftaran_nomor_antrian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='nama_dokter',
            field=models.CharField(max_length=50),
        ),
        migrations.RenameField(
            model_name='pasien',
            old_name='tanggal_lahir',
            new_name='birth',
        ),
        migrations.RenameField(
            model_name='pasien',
            old_name='email_pasien',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='pasien',
            old_name='jenis_kelamin',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='pasien',
            old_name='nama',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pasien',
            old_name='nomor_HP',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='pendaftaran',
            old_name='id_bpjs',
            new_name='id_pasien',
        ),
        migrations.RenameField(
            model_name='perawat',
            old_name='email_perawat',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='perawat',
            old_name='nama_perawat',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='perawat',
            old_name='password_perawat',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='pasien',
            name='ID_BPJS',
        ),
        migrations.RemoveField(
            model_name='pendaftaran',
            name='hari_konsul_dokter',
        ),
        migrations.RemoveField(
            model_name='pendaftaran',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pendaftaran',
            name='nama_pasien',
        ),
        migrations.RemoveField(
            model_name='pendaftaran',
            name='sesi_praktek_dokter',
        ),
        migrations.RemoveField(
            model_name='perawat',
            name='id_perawat',
        ),
        migrations.AddField(
            model_name='pasien',
            name='id',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='id_pendaftaran',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='perawat',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='data_pasien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_pasien_set', to='RSUD_KRATON.pendaftaran'),
        ),
        migrations.CreateModel(
            name='Dokter_spesialis',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=15)),
                ('image', models.CharField(max_length=50)),
                ('specialty', models.CharField(max_length=100)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_spesialis_set', to='RSUD_KRATON.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Dokter_umum',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=15)),
                ('image', models.CharField(max_length=50)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_umum_set', to='RSUD_KRATON.schedule')),
            ],
        ),
        migrations.DeleteModel(
            name='Dokter',
        ),
    ]
