# Generated by Django 5.1.6 on 2025-05-18 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0003_pendaftaran_sesi_praktek_data_pendaftaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasien',
            name='diagnosa_icd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pasien', to='RSUD_KRATON.icd'),
        ),
    ]
