# Generated by Django 5.2 on 2025-04-27 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0004_dokter_spesialis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokter',
            name='image_dokter',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dokter',
            name='schedule_dokter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_dokter_set', to='RSUD_KRATON.schedule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dokter_spesialis',
            name='image_dokter_spc',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dokter_spesialis',
            name='schedule_dokter_spc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_dokter_spc_set', to='RSUD_KRATON.schedule'),
            preserve_default=False,
        ),
    ]
