# Generated by Django 5.1.7 on 2025-04-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0004_alter_pendaftaran_nama_dokter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
