# Generated by Django 5.1.6 on 2025-05-18 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0004_pasien_diagnosa_icd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasien',
            name='diagnosa_icd',
        ),
        migrations.CreateModel(
            name='Laporan_icd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosa_icd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pasien', to='RSUD_KRATON.icd')),
            ],
        ),
    ]
