# Generated by Django 5.2 on 2025-04-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0005_dokter_image_dokter_dokter_schedule_dokter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='schedule_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
