# Generated by Django 5.1.7 on 2025-04-26 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0005_alter_diagnosa_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosa',
            old_name='id_pendaftaran',
            new_name='data_pendaftaran',
        ),
        migrations.RemoveField(
            model_name='diagnosa',
            name='nama_pasien',
        ),
        migrations.AddField(
            model_name='diagnosa',
            name='data_pasien',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nama_pasien_set', to='RSUD_KRATON.pasien'),
            preserve_default=False,
        ),
    ]
