# Generated by Django 5.1.7 on 2025-04-26 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0006_rename_id_pendaftaran_diagnosa_data_pendaftaran_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendaftaran',
            old_name='id_pendaftaran',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='diagnosa',
            name='data_pasien',
        ),
    ]
