# Generated by Django 5.2 on 2025-04-27 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0006_schedule_schedule_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokter',
            name='schedule_dokter',
        ),
        migrations.RemoveField(
            model_name='dokter_spesialis',
            name='schedule_dokter_spc',
        ),
    ]
