# Generated by Django 5.1.6 on 2025-05-18 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0006_pasien_diagnosa_icd_delete_laporan_icd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasien',
            name='diagnosa_icd',
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='diagnosa_icd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pasien', to='RSUD_KRATON.icd'),
        ),
    ]
