# Generated by Django 5.2 on 2025-04-27 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0007_remove_dokter_schedule_dokter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokter',
            name='image_dokter',
        ),
        migrations.RemoveField(
            model_name='dokter_spesialis',
            name='image_dokter_spc',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='schedule_id',
        ),
    ]
