# Generated by Django 5.2 on 2025-05-27 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0007_remove_pasien_diagnosa_icd_pendaftaran_diagnosa_icd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendaftaran',
            name='diagnosa_icd',
        ),
    ]
