# Generated by Django 5.1.7 on 2025-04-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0007_rename_id_pendaftaran_pendaftaran_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosa',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
