# Generated by Django 5.1.6 on 2025-06-09 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0008_remove_pendaftaran_diagnosa_icd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokter',
            name='schedule_dokter',
        ),
        migrations.RemoveField(
            model_name='dokter_spesialis',
            name='schedule_dokter',
        ),
        migrations.CreateModel(
            name='schedule_praktek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jam_mulai', models.CharField(max_length=100)),
                ('jam_selesai', models.CharField(max_length=100)),
                ('Dokter_spesialis', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dokter_umum_praktek_set', to='RSUD_KRATON.dokter_spesialis')),
                ('data_pendaftaran', models.ManyToManyField(blank=True, related_name='data_pendaftaran_set', to='RSUD_KRATON.pendaftaran')),
                ('dokter_umum', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dokter_umum_praktek_set', to='RSUD_KRATON.dokter')),
                ('hari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hari_praktek_set', to='RSUD_KRATON.hari_praktek')),
            ],
        ),
        migrations.DeleteModel(
            name='sesi_praktek',
        ),
    ]
