# Generated by Django 5.1.7 on 2025-04-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0008_alter_diagnosa_id_alter_pendaftaran_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasien',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
