# Generated by Django 5.2 on 2025-06-10 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0010_alter_schedule_praktek_dokter_spesialis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule_praktek',
            old_name='Dokter_spesialis',
            new_name='dokter_spesialis',
        ),
    ]
