# Generated by Django 5.1.6 on 2025-06-10 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0010_alter_schedule_praktek_dokter_spesialis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule_praktek',
            old_name='Dokter_spesialis',
            new_name='dokter_spesialis',
        ),
        migrations.RemoveField(
            model_name='pendaftaran',
            name='sesi_praktek_dokter',
        ),
    ]
