# Generated by Django 5.1.7 on 2025-04-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0010_alter_diagnosa_id_alter_pendaftaran_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dokter_spesialis',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dokter_umum',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='perawat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
