# Generated by Django 5.2 on 2025-04-27 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0010_remove_schedule_data_pasien_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendaftaran',
            name='id_pendaftaran',
        ),
    ]
