# Generated by Django 5.2 on 2025-04-27 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0011_remove_pendaftaran_id_pendaftaran'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosa',
            old_name='id_pendaftaran',
            new_name='data_pendaftaran',
        ),
        migrations.RenameField(
            model_name='diagnosa',
            old_name='penyakit_pasien',
            new_name='diagnosa_subjektif',
        ),
        migrations.RemoveField(
            model_name='diagnosa',
            name='diagnosa_icd',
        ),
        migrations.RemoveField(
            model_name='diagnosa',
            name='kode_icd',
        ),
        migrations.RemoveField(
            model_name='diagnosa',
            name='nama_pasien',
        ),
        migrations.AddField(
            model_name='diagnosa',
            name='diagnosa_icd_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosa_icd_1_set', to='RSUD_KRATON.icd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnosa',
            name='diagnosa_icd_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosa_icd_2_set', to='RSUD_KRATON.icd'),
            preserve_default=False,
        ),
    ]
