# Generated by Django 5.1.6 on 2025-06-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0011_rename_dokter_spesialis_schedule_praktek_dokter_spesialis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule_praktek',
            name='hari',
        ),
        migrations.AddField(
            model_name='schedule_praktek',
            name='hari',
            field=models.ManyToManyField(related_name='hari_praktek_set', to='RSUD_KRATON.hari_praktek'),
        ),
    ]
