# Generated by Django 5.2 on 2025-04-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0012_rename_id_pendaftaran_diagnosa_data_pendaftaran_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='sesi_praktek_dokter',
            field=models.CharField(max_length=50),
        ),
    ]
