# Generated by Django 5.2 on 2025-06-10 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0013_remove_schedule_praktek_dokter_spesialis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule_praktek',
            name='dokter_spesialis',
        ),
        migrations.RemoveField(
            model_name='schedule_praktek',
            name='dokter_umum',
        ),
        migrations.RemoveField(
            model_name='schedule_praktek',
            name='hari',
        ),
        migrations.AddField(
            model_name='schedule_praktek',
            name='dokter_spesialis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dokter_spesialis_praktek_set', to='RSUD_KRATON.dokter'),
        ),
        migrations.AddField(
            model_name='schedule_praktek',
            name='dokter_umum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dokter_umum_praktek_set', to='RSUD_KRATON.dokter'),
        ),
        migrations.AddField(
            model_name='schedule_praktek',
            name='hari',
            field=models.ForeignKey(default=(117), on_delete=django.db.models.deletion.CASCADE, related_name='hari_praktek_set', to='RSUD_KRATON.hari_praktek'),
            preserve_default=False,
        ),
    ]
