# Generated by Django 5.2 on 2025-04-27 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0013_alter_pendaftaran_sesi_praktek_dokter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perawat',
            name='id_perawat',
        ),
    ]
