# Generated by Django 5.2 on 2025-06-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0014_remove_schedule_praktek_dokter_spesialis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftaran',
            name='sesi_praktek_dokter',
            field=models.CharField(default='10.00 - 14.00', max_length=50),
            preserve_default=False,
        ),
    ]
