# Generated by Django 5.2 on 2025-04-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0015_dokter_image_dokter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='data_pendaftaran',
        ),
        migrations.AddField(
            model_name='schedule',
            name='data_pendaftaran',
            field=models.ManyToManyField(related_name='data_pendaftaran_set', to='RSUD_KRATON.pendaftaran'),
        ),
    ]
