# Generated by Django 5.1.6 on 2025-06-11 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0015_pendaftaran_sesi_praktek_dokter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule_praktek',
            name='dokter_spesialis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dokter_spesialis_praktek_set', to='RSUD_KRATON.dokter_spesialis'),
        ),
    ]
