# Generated by Django 5.1.6 on 2025-06-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0016_alter_schedule_praktek_dokter_spesialis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spesialisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_spesialisasi', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule_praktek',
            name='dokter_spesialis',
        ),
        migrations.RemoveField(
            model_name='history',
            name='Dokter_spesialis',
        ),
        migrations.DeleteModel(
            name='Dokter_spesialis',
        ),
    ]
