# Generated by Django 5.2 on 2025-04-27 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0016_remove_schedule_data_pendaftaran_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokter',
            name='id_dokter',
        ),
        migrations.RemoveField(
            model_name='dokter_spesialis',
            name='id_dokter_spc',
        ),
    ]
