# Generated by Django 5.2 on 2025-04-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0017_remove_dokter_id_dokter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='data_pendaftaran',
            field=models.ManyToManyField(blank=True, related_name='data_pendaftaran_set', to='RSUD_KRATON.pendaftaran'),
        ),
    ]
