# Generated by Django 5.1.6 on 2025-06-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0017_spesialisasi_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rekap_medis',
        ),
    ]
