# Generated by Django 5.1.6 on 2025-06-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0018_delete_rekap_medis'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasien',
            name='rekap_medis',
            field=models.ManyToManyField(blank=True, related_name='rekap_medis_set', to='RSUD_KRATON.history'),
        ),
    ]
