# Generated by Django 5.1.7 on 2025-04-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0018_alter_schedule_data_pendaftaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokter_spesialis',
            name='spesialization',
            field=models.CharField(default='Dokter Bedah', max_length=20),
            preserve_default=False,
        ),
    ]
