# Generated by Django 5.1.7 on 2025-04-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0019_dokter_spesialis_spesialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokter',
            name='email_dokter',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dokter_spesialis',
            name='email_dokter_spc',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hari_praktek',
            name='hari',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='email_pasien',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='perawat',
            name='email_perawat',
            field=models.CharField(max_length=50),
        ),
    ]
