# Generated by Django 5.1.6 on 2025-06-18 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0019_pasien_rekap_medis'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokter',
            name='spesialisasi',
            field=models.ForeignKey(blank='True', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='spesialisasi_dokter_set', to='RSUD_KRATON.spesialisasi'),
            preserve_default=False,
        ),
    ]
