# Generated by Django 5.2 on 2025-04-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0019_dokter_spesialis_spesialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='hari_praktek_dokter',
        ),
        migrations.AddField(
            model_name='schedule',
            name='hari_praktek_dokter',
            field=models.ManyToManyField(related_name='hari_praktek_dokter_set', to='RSUD_KRATON.hari_praktek'),
        ),
    ]
