# Generated by Django 5.1.6 on 2025-06-18 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0020_dokter_spesialisasi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dokter',
            old_name='spesialisasi',
            new_name='spesialisasi_dokter',
        ),
    ]
