# Generated by Django 5.1.7 on 2025-04-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0020_alter_dokter_email_dokter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hari_praktek',
            name='hari',
            field=models.CharField(max_length=50),
        ),
    ]
