# Generated by Django 5.1.7 on 2025-04-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0021_alter_hari_praktek_hari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hari_praktek',
            name='hari',
            field=models.JSONField(default=list),
        ),
    ]
