# Generated by Django 5.1.7 on 2025-04-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0022_alter_hari_praktek_hari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hari_praktek',
            name='hari',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='hari_praktek_dokter',
        ),
        migrations.AddField(
            model_name='schedule',
            name='hari_praktek_dokter',
            field=models.ManyToManyField(related_name='hari_praktek_dokter_set', to='RSUD_KRATON.hari_praktek'),
        ),
    ]
