# Generated by Django 5.1.7 on 2025-04-30 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0020_remove_schedule_hari_praktek_dokter_and_more'),
        ('RSUD_KRATON', '0023_alter_hari_praktek_hari_and_more'),
    ]

    operations = [
    ]
