# Generated by Django 5.1.7 on 2025-04-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0024_merge_20250430_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='jam_total',
        ),
        migrations.AddField(
            model_name='hari_praktek',
            name='jam_total',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
    ]
