# Generated by Django 5.2 on 2025-04-30 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0024_merge_20250430_1257'),
        ('RSUD_KRATON', '0025_remove_schedule_jam_total_hari_praktek_jam_total'),
    ]

    operations = [
    ]
