# Generated by Django 5.2 on 2025-04-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0026_merge_20250430_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokter',
            name='image_dokter',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dokter_spesialis',
            name='image_dokter_spc',
            field=models.CharField(max_length=100),
        ),
    ]
