# Generated by Django 5.1.7 on 2025-05-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0027_alter_dokter_image_dokter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasien',
            name='nomor_urut',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
