# Generated by Django 5.1.7 on 2025-05-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0029_alter_pasien_nomor_urut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasien',
            name='nomor_urut',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
