# Generated by Django 5.2 on 2025-05-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0030_alter_pasien_nomor_urut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='data_pendaftaran',
        ),
        migrations.AddField(
            model_name='hari_praktek',
            name='data_pendaftaran',
            field=models.ManyToManyField(blank=True, related_name='data_pendaftaran_set', to='RSUD_KRATON.pendaftaran'),
        ),
    ]
