# Generated by Django 5.2 on 2025-05-16 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0031_remove_schedule_data_pendaftaran_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hari_praktek',
            name='data_pendaftaran',
        ),
        migrations.RemoveField(
            model_name='hari_praktek',
            name='jam_total',
        ),
        migrations.RemoveField(
            model_name='hari_praktek',
            name='sesi_praktek',
        ),
        migrations.CreateModel(
            name='sesi_praktek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jam_sesi', models.CharField(max_length=50)),
                ('jam_total', models.IntegerField()),
                ('data_pendaftaran', models.ManyToManyField(blank=True, related_name='data_pendaftaran_set', to='RSUD_KRATON.pendaftaran')),
                ('hari_praktek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hari_praktek_set', to='RSUD_KRATON.hari_praktek')),
            ],
        ),
    ]
