# Generated by Django 5.2 on 2025-05-16 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0032_remove_hari_praktek_data_pendaftaran_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokter',
            name='schedule_dokter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hari_praktek_dokter_set', to='RSUD_KRATON.hari_praktek'),
        ),
        migrations.AlterField(
            model_name='dokter_spesialis',
            name='schedule_dokter_spc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hari_praktek_dokter_spc_set', to='RSUD_KRATON.hari_praktek'),
        ),
        migrations.DeleteModel(
            name='schedule',
        ),
    ]
