# Generated by Django 5.2 on 2025-05-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0033_alter_dokter_schedule_dokter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokter',
            name='schedule_dokter',
        ),
        migrations.RemoveField(
            model_name='dokter_spesialis',
            name='schedule_dokter_spc',
        ),
        migrations.AddField(
            model_name='dokter',
            name='schedule_dokter',
            field=models.ManyToManyField(related_name='hari_praktek_dokter_set', to='RSUD_KRATON.hari_praktek'),
        ),
        migrations.AddField(
            model_name='dokter_spesialis',
            name='schedule_dokter_spc',
            field=models.ManyToManyField(related_name='hari_praktek_dokter_spc_set', to='RSUD_KRATON.hari_praktek'),
        ),
    ]
