# Generated by Django 5.1.6 on 2025-05-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0034_remove_dokter_schedule_dokter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokter_spesialis',
            name='spesialization',
            field=models.CharField(max_length=100),
        ),
    ]
