# Generated by Django 5.1.6 on 2025-05-16 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSUD_KRATON', '0035_alter_dokter_spesialis_spesialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icd',
            name='kode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='icd',
            name='nama_diagnosa',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_konsultasi', models.DateField()),
                ('keluhan', models.CharField(max_length=100)),
                ('diagnosa_sub', models.CharField(max_length=200)),
                ('diagnosa_primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosa_primary_set', to='RSUD_KRATON.icd')),
                ('diagnosa_secondary', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosa_secondary_set', to='RSUD_KRATON.icd')),
            ],
        ),
        migrations.CreateModel(
            name='rekap_medis',
            fields=[
                ('ID_BPJS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pasien_set', serialize=False, to='RSUD_KRATON.pasien')),
                ('history', models.ManyToManyField(related_name='history_set', to='RSUD_KRATON.history')),
                ('id_dokter_spesialis', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dokter_spesialis_set', to='RSUD_KRATON.dokter_spesialis')),
                ('id_dokter_umum', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dokter_umum_set', to='RSUD_KRATON.dokter')),
            ],
        ),
        migrations.DeleteModel(
            name='Diagnosa',
        ),
    ]
